version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: todo_frontend
    ports:
      - "3000:80"
    networks:
      - app_network

  backend:
    build:
      context: ./backend
    container_name: todo_backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - app_network

  database:
    image: mongo:5.0
    container_name: todo_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # Attach the named volume
    networks:
      - app_network

volumes:
  mongo_data: # Define the named volume for MongoDB

networks:
  app_network: # Shared network for container communication
